In [2]:
import pandas as pd
pd.set_option('display.max_rows', 103)
pd.set_option('display.max_columns', 50)

In [3]:
def re_index(df):
    df.reset

In [4]:
df = pd.read_csv("All-India_-Crop-wise-Area,-Production-&-Yield.csv",index_col = 0)
df

,Season,Area-2020-21,Area-2021-22,Area-2022-23,Area-2023-24,Area-2024-25,Production-2020-21,Production-2021-22,Production-2022-23,Production-2023-24,Production-2024-25,Yield-2020-21,Yield-2021-22,Yield-2022-23,Yield-2023-24,Yield-2024-25
Crop,,,,,,,,,,,,,,,,
Rice,Kharif,403.58,410.38,404.03,407.34,434.13,1052.08,1110.01,1105.12,1132.59,1218.54,2607.0,2705.0,2735.0,2780.0,2807.0
Rice,Rabi,54.11,52.40,43.28,40.76,44.74,191.60,184.71,150.04,146.01,156.72,3541.0,3525.0,3467.0,3582.0,3503.0
Rice,Summer,NaN,NaN,31.01,30.18,35.36,NaN,NaN,102.40,99.65,115.48,NaN,NaN,3302.0,3302.0,3265.0
Rice,Total,457.69,462.79,478.32,478.28,514.23,1243.68,1294.71,1357.55,1378.25,1490.74,2717.0,2798.0,2838.0,2882.0,2899.0
Wheat,Rabi,311.25,304.59,314.01,318.33,327.61,1095.86,1077.42,1105.54,1132.92,1175.07,3521.0,3537.0,3521.0,3559.0,3587.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Tobacco,Total,NaN,3.86,3.79,4.10,NaN,NaN,8.18,7.70,8.66,NaN,NaN,2118.0,2029.0,2109.0,NaN
Sannhemp,Kharif,NaN,0.13,0.12,0.09,NaN,NaN,0.51,0.46,0.40,NaN,NaN,722.0,703.0,801.0,NaN
Sannhemp,Total,NaN,0.13,0.12,0.09,NaN,NaN,0.51,0.46,0.40,NaN,NaN,722.0,703.0,801.0,NaN
Guarseed,Kharif,NaN,26.30,32.13,30.89,NaN,NaN,11.83,17.87,16.65,NaN,NaN,450.0,556.0,539.0,NaN
Guarseed,Total,NaN,26.30,32.13,30.89,NaN,NaN,11.83,17.87,16.65,NaN,NaN,450.0,556.0,539.0,NaN

In [5]:
df = df[df.Season == "Total"]
df

,Season,Area-2020-21,Area-2021-22,Area-2022-23,Area-2023-24,Area-2024-25,Production-2020-21,Production-2021-22,Production-2022-23,Production-2023-24,Production-2024-25,Yield-2020-21,Yield-2021-22,Yield-2022-23,Yield-2023-24,Yield-2024-25
Crop,,,,,,,,,,,,,,,,
Rice,Total,457.69,462.79,478.32,478.28,514.23,1243.68,1294.71,1357.55,1378.25,1490.74,2717.0,2798.0,2838.0,2882.0,2899.0
Wheat,Total,311.25,304.59,314.01,318.33,327.61,1095.86,1077.42,1105.54,1132.92,1175.07,3521.0,3537.0,3521.0,3559.0,3587.0
Maize,Total,98.92,99.58,107.44,112.41,120.17,316.47,337.30,380.85,376.65,422.81,3199.0,3387.0,3545.0,3351.0,3518.0
Barley,Total,5.92,4.53,6.28,5.51,6.05,16.56,13.71,19.13,16.99,18.44,2796.0,3025.0,3044.0,3082.0,3049.0
Jowar,Total,43.78,38.01,35.35,40.76,39.84,48.12,41.51,38.14,47.37,48.80,1099.0,1092.0,1079.0,1162.0,1225.0
Bajra,Total,76.52,68.41,75.72,73.75,72.10,108.63,97.81,114.31,107.16,108.63,1420.0,1430.0,1510.0,1453.0,1507.0
Ragi,Total,11.59,12.18,11.63,12.15,12.29,19.98,17.01,16.91,16.70,18.34,1724.0,1396.0,1454.0,1375.0,1492.0
Small Millets,Total,4.44,4.29,4.28,4.80,4.42,3.47,3.67,3.84,4.49,4.38,781.0,857.0,898.0,935.0,992.0
Shree Anna /Nutri Cereals,Total,136.33,122.89,126.98,131.45,128.64,180.21,160.00,173.21,175.72,180.15,1322.0,1302.0,1364.0,1337.0,1400.0
Nutri/Coarse Cereals,Total,241.18,227.00,240.70,249.38,254.86,513.24,511.01,573.19,569.36,621.40,2128.0,2251.0,2381.0,2283.0,2438.0
Cereals,Total,1010.12,994.37,1033.03,1045.99,1096.70,2852.79,2883.14,3036.28,3080.52,3287.21,2824.0,2899.0,2939.0,2945.0,2997.0
Tur,Total,47.24,49.00,40.68,41.31,43.28,43.16,42.20,33.12,34.17,35.61,914.0,861.0,814.0,827.0,823.0
Gram,Total,99.96,107.40,104.71,95.87,96.08,119.11,135.44,122.67,110.39,113.37,1192.0,1261.0,1172.0,1151.0,1180.0
Urad,Total,41.43,46.33,40.02,35.36,30.23,22.30,27.76,26.31,23.19,21.06,538.0,599.0,657.0,656.0,697.0
Moong,Total,51.30,55.51,55.46,51.87,55.72,30.85,31.66,36.76,31.03,38.19,601.0,570.0,663.0,598.0,685.0
Lentil,Total,14.68,14.12,16.37,17.43,17.06,14.94,12.69,15.59,17.91,17.72,1017.0,899.0,952.0,1028.0,1038.0
Other Pulses,Total,33.22,34.95,31.77,33.22,33.86,24.27,23.27,26.14,25.77,26.43,731.0,666.0,823.0,776.0,781.0
Total Pulses,Total,287.83,307.31,289.01,275.05,276.24,254.63,273.02,260.58,242.46,252.38,885.0,888.0,902.0,881.0,914.0
Total Food Grains,Total,1297.95,1301.69,1322.04,1321.04,1372.94,3107.42,3156.16,3296.87,3322.98,3539.59,2394.0,2425.0,2494.0,2515.0,2578.0
Groundnut,Total,60.15,57.05,49.61,47.07,57.54,102.44,101.35,102.97,101.80,118.96,1703.0,1777.0,2075.0,2163.0,2067.0
Castorseed,Total,8.87,8.31,10.19,10.41,9.31,16.47,16.19,19.80,19.59,17.30,1856.0,1948.0,1942.0,1881.0,1858.0
Sesamum,Total,17.23,16.27,15.23,15.31,15.33,8.17,7.89,8.02,8.47,8.29,474.0,485.0,527.0,553.0,541.0
Nigerseed,Total,1.34,0.97,0.88,0.83,0.51,0.42,0.33,0.29,0.27,0.15,317.0,337.0,325.0,323.0,292.0
Soybean,Total,129.18,121.47,130.84,132.55,129.57,126.10,129.87,149.85,130.62,151.80,976.0,1069.0,1145.0,985.0,1172.0
Sunflower,Total,2.26,2.71,3.64,1.51,1.74,2.28,2.50,3.63,1.73,1.96,1011.0,923.0,996.0,1144.0,1129.0
Rapeseed & Mustard,Total,67.00,79.91,88.52,91.83,86.29,102.10,119.63,126.43,132.59,126.06,1524.0,1497.0,1428.0,1444.0,1461.0
Linseed,Total,1.75,1.97,2.39,1.75,1.78,1.11,1.26,1.67,1.13,1.13,637.0,642.0,698.0,644.0,633.0
Safflower,Total,0.56,0.79,1.09,0.65,0.57,0.36,0.61,0.90,0.50,0.43,640.0,777.0,826.0,768.0,756.0
Total Oil Seeds,Total,288.34,289.45,302.39,301.92,302.65,359.46,379.63,413.55,396.69,426.09,1247.0,1312.0,1368.0,1314.0,1408.0
Sugarcane,Total,48.51,51.75,58.85,57.40,53.58,4053.99,4394.25,4905.33,4531.58,4501.16,83566.0,84906.0,83349.0,78953.0,84006.0
Cotton,Total,132.86,123.72,129.27,126.88,112.30,352.48,311.18,336.60,325.22,306.92,451.0,428.0,443.0,436.0,465.0
Jute,Total,6.22,6.29,6.19,5.98,5.39,89.53,97.62,89.89,92.52,84.33,2591.0,2793.0,2614.0,2783.0,2814.0
Mesta,Total,0.41,0.38,0.39,0.39,0.31,4.02,3.87,4.03,4.41,3.15,1782.0,1831.0,1871.0,2033.0,1816.0
Jute & Mesta,Total,6.62,6.67,6.58,6.37,5.71,93.54,101.49,93.92,96.92,87.47,2542.0,2738.0,2570.0,2737.0,2759.0
Tobacco,Total,NaN,3.86,3.79,4.10,NaN,NaN,8.18,7.70,8.66,NaN,NaN,2118.0,2029.0,2109.0,NaN
Sannhemp,Total,NaN,0.13,0.12,0.09,NaN,NaN,0.51,0.46,0.40,NaN,NaN,722.0,703.0,801.0,NaN
Guarseed,Total,NaN,26.30,32.13,30.89,NaN,NaN,11.83,17.87,16.65,NaN,NaN,450.0,556.0,539.0,NaN

In [6]:
df.columns

Index(['Season', 'Area-2020-21', 'Area-2021-22', 'Area-2022-23',
       'Area-2023-24', 'Area-2024-25', 'Production-2020-21',
       'Production-2021-22', 'Production-2022-23', 'Production-2023-24',
       'Production-2024-25', 'Yield-2020-21', 'Yield-2021-22', 'Yield-2022-23',
       'Yield-2023-24', 'Yield-2024-25'],
      dtype='object')

In [7]:
df_Area = df[['Area-2020-21', 'Area-2021-22', 'Area-2022-23',
                'Area-2023-24', 'Area-2024-25']]

df_Area.columns = ['2020', '2021', '2022', '2023',
                    '2024']
df_Area = df_Area.T

df_Area.index.name = 'Year'

df_Area.columns = [i.upper() + " " +"AREA" for i in df_Area.columns]

df_Area

,RICE AREA,WHEAT AREA,MAIZE AREA,BARLEY AREA,JOWAR AREA,BAJRA AREA,RAGI AREA,SMALL MILLETS AREA,SHREE ANNA /NUTRI CEREALS AREA,NUTRI/COARSE CEREALS AREA,CEREALS AREA,TUR AREA,GRAM AREA,URAD AREA,MOONG AREA,LENTIL AREA,OTHER PULSES AREA,TOTAL PULSES AREA,TOTAL FOOD GRAINS AREA,GROUNDNUT AREA,CASTORSEED AREA,SESAMUM AREA,NIGERSEED AREA,SOYBEAN AREA,SUNFLOWER AREA,RAPESEED & MUSTARD AREA,LINSEED AREA,SAFFLOWER AREA,TOTAL OIL SEEDS AREA,SUGARCANE AREA,COTTON AREA,JUTE AREA,MESTA AREA,JUTE & MESTA AREA,TOBACCO AREA,SANNHEMP AREA,GUARSEED AREA
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020,457.69,311.25,98.92,5.92,43.78,76.52,11.59,4.44,136.33,241.18,1010.12,47.24,99.96,41.43,51.30,14.68,33.22,287.83,1297.95,60.15,8.87,17.23,1.34,129.18,2.26,67.00,1.75,0.56,288.34,48.51,132.86,6.22,0.41,6.62,NaN,NaN,NaN
2021,462.79,304.59,99.58,4.53,38.01,68.41,12.18,4.29,122.89,227.00,994.37,49.00,107.40,46.33,55.51,14.12,34.95,307.31,1301.69,57.05,8.31,16.27,0.97,121.47,2.71,79.91,1.97,0.79,289.45,51.75,123.72,6.29,0.38,6.67,3.86,0.13,26.30
2022,478.32,314.01,107.44,6.28,35.35,75.72,11.63,4.28,126.98,240.70,1033.03,40.68,104.71,40.02,55.46,16.37,31.77,289.01,1322.04,49.61,10.19,15.23,0.88,130.84,3.64,88.52,2.39,1.09,302.39,58.85,129.27,6.19,0.39,6.58,3.79,0.12,32.13
2023,478.28,318.33,112.41,5.51,40.76,73.75,12.15,4.80,131.45,249.38,1045.99,41.31,95.87,35.36,51.87,17.43,33.22,275.05,1321.04,47.07,10.41,15.31,0.83,132.55,1.51,91.83,1.75,0.65,301.92,57.40,126.88,5.98,0.39,6.37,4.10,0.09,30.89
2024,514.23,327.61,120.17,6.05,39.84,72.10,12.29,4.42,128.64,254.86,1096.70,43.28,96.08,30.23,55.72,17.06,33.86,276.24,1372.94,57.54,9.31,15.33,0.51,129.57,1.74,86.29,1.78,0.57,302.65,53.58,112.30,5.39,0.31,5.71,NaN,NaN,NaN

In [8]:
df_Production = df[['Production-2020-21',
       'Production-2021-22', 'Production-2022-23', 'Production-2023-24',
       'Production-2024-25']]

df_Production.columns = ['2020', '2021', '2022', '2023',
                    '2024']
df_Production = df_Production.T

df_Production.index.name = 'Year'

df_Production.columns = [i.upper() + " " +"PRODUCTION" for i in df_Production.columns]

df_Production

,RICE PRODUCTION,WHEAT PRODUCTION,MAIZE PRODUCTION,BARLEY PRODUCTION,JOWAR PRODUCTION,BAJRA PRODUCTION,RAGI PRODUCTION,SMALL MILLETS PRODUCTION,SHREE ANNA /NUTRI CEREALS PRODUCTION,NUTRI/COARSE CEREALS PRODUCTION,CEREALS PRODUCTION,TUR PRODUCTION,GRAM PRODUCTION,URAD PRODUCTION,MOONG PRODUCTION,LENTIL PRODUCTION,OTHER PULSES PRODUCTION,TOTAL PULSES PRODUCTION,TOTAL FOOD GRAINS PRODUCTION,GROUNDNUT PRODUCTION,CASTORSEED PRODUCTION,SESAMUM PRODUCTION,NIGERSEED PRODUCTION,SOYBEAN PRODUCTION,SUNFLOWER PRODUCTION,RAPESEED & MUSTARD PRODUCTION,LINSEED PRODUCTION,SAFFLOWER PRODUCTION,TOTAL OIL SEEDS PRODUCTION,SUGARCANE PRODUCTION,COTTON PRODUCTION,JUTE PRODUCTION,MESTA PRODUCTION,JUTE & MESTA PRODUCTION,TOBACCO PRODUCTION,SANNHEMP PRODUCTION,GUARSEED PRODUCTION
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020,1243.68,1095.86,316.47,16.56,48.12,108.63,19.98,3.47,180.21,513.24,2852.79,43.16,119.11,22.30,30.85,14.94,24.27,254.63,3107.42,102.44,16.47,8.17,0.42,126.10,2.28,102.10,1.11,0.36,359.46,4053.99,352.48,89.53,4.02,93.54,NaN,NaN,NaN
2021,1294.71,1077.42,337.30,13.71,41.51,97.81,17.01,3.67,160.00,511.01,2883.14,42.20,135.44,27.76,31.66,12.69,23.27,273.02,3156.16,101.35,16.19,7.89,0.33,129.87,2.50,119.63,1.26,0.61,379.63,4394.25,311.18,97.62,3.87,101.49,8.18,0.51,11.83
2022,1357.55,1105.54,380.85,19.13,38.14,114.31,16.91,3.84,173.21,573.19,3036.28,33.12,122.67,26.31,36.76,15.59,26.14,260.58,3296.87,102.97,19.80,8.02,0.29,149.85,3.63,126.43,1.67,0.90,413.55,4905.33,336.60,89.89,4.03,93.92,7.70,0.46,17.87
2023,1378.25,1132.92,376.65,16.99,47.37,107.16,16.70,4.49,175.72,569.36,3080.52,34.17,110.39,23.19,31.03,17.91,25.77,242.46,3322.98,101.80,19.59,8.47,0.27,130.62,1.73,132.59,1.13,0.50,396.69,4531.58,325.22,92.52,4.41,96.92,8.66,0.40,16.65
2024,1490.74,1175.07,422.81,18.44,48.80,108.63,18.34,4.38,180.15,621.40,3287.21,35.61,113.37,21.06,38.19,17.72,26.43,252.38,3539.59,118.96,17.30,8.29,0.15,151.80,1.96,126.06,1.13,0.43,426.09,4501.16,306.92,84.33,3.15,87.47,NaN,NaN,NaN

In [9]:
df_Yield = df[['Yield-2020-21', 'Yield-2021-22', 'Yield-2022-23',
       'Yield-2023-24', 'Yield-2024-25']]

df_Yield.columns = ['2020', '2021', '2022', '2023',
                    '2024']
df_Yield = df_Yield.T

df_Yield.index.name = 'Year'

df_Yield.columns = [i.upper() + " " +"YIELD" for i in df_Yield.columns]

df_Yield

,RICE YIELD,WHEAT YIELD,MAIZE YIELD,BARLEY YIELD,JOWAR YIELD,BAJRA YIELD,RAGI YIELD,SMALL MILLETS YIELD,SHREE ANNA /NUTRI CEREALS YIELD,NUTRI/COARSE CEREALS YIELD,CEREALS YIELD,TUR YIELD,GRAM YIELD,URAD YIELD,MOONG YIELD,LENTIL YIELD,OTHER PULSES YIELD,TOTAL PULSES YIELD,TOTAL FOOD GRAINS YIELD,GROUNDNUT YIELD,CASTORSEED YIELD,SESAMUM YIELD,NIGERSEED YIELD,SOYBEAN YIELD,SUNFLOWER YIELD,RAPESEED & MUSTARD YIELD,LINSEED YIELD,SAFFLOWER YIELD,TOTAL OIL SEEDS YIELD,SUGARCANE YIELD,COTTON YIELD,JUTE YIELD,MESTA YIELD,JUTE & MESTA YIELD,TOBACCO YIELD,SANNHEMP YIELD,GUARSEED YIELD
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020,2717.0,3521.0,3199.0,2796.0,1099.0,1420.0,1724.0,781.0,1322.0,2128.0,2824.0,914.0,1192.0,538.0,601.0,1017.0,731.0,885.0,2394.0,1703.0,1856.0,474.0,317.0,976.0,1011.0,1524.0,637.0,640.0,1247.0,83566.0,451.0,2591.0,1782.0,2542.0,NaN,NaN,NaN
2021,2798.0,3537.0,3387.0,3025.0,1092.0,1430.0,1396.0,857.0,1302.0,2251.0,2899.0,861.0,1261.0,599.0,570.0,899.0,666.0,888.0,2425.0,1777.0,1948.0,485.0,337.0,1069.0,923.0,1497.0,642.0,777.0,1312.0,84906.0,428.0,2793.0,1831.0,2738.0,2118.0,722.0,450.0
2022,2838.0,3521.0,3545.0,3044.0,1079.0,1510.0,1454.0,898.0,1364.0,2381.0,2939.0,814.0,1172.0,657.0,663.0,952.0,823.0,902.0,2494.0,2075.0,1942.0,527.0,325.0,1145.0,996.0,1428.0,698.0,826.0,1368.0,83349.0,443.0,2614.0,1871.0,2570.0,2029.0,703.0,556.0
2023,2882.0,3559.0,3351.0,3082.0,1162.0,1453.0,1375.0,935.0,1337.0,2283.0,2945.0,827.0,1151.0,656.0,598.0,1028.0,776.0,881.0,2515.0,2163.0,1881.0,553.0,323.0,985.0,1144.0,1444.0,644.0,768.0,1314.0,78953.0,436.0,2783.0,2033.0,2737.0,2109.0,801.0,539.0
2024,2899.0,3587.0,3518.0,3049.0,1225.0,1507.0,1492.0,992.0,1400.0,2438.0,2997.0,823.0,1180.0,697.0,685.0,1038.0,781.0,914.0,2578.0,2067.0,1858.0,541.0,292.0,1172.0,1129.0,1461.0,633.0,756.0,1408.0,84006.0,465.0,2814.0,1816.0,2759.0,NaN,NaN,NaN

In [10]:
l = []
i=0
while i < 37:
    l.append(df_Area.columns[i])
    l.append(df_Production.columns[i])
    l.append(df_Yield.columns[i])
    i = i+1
print(l)

['RICE AREA', 'RICE PRODUCTION', 'RICE YIELD', 'WHEAT AREA', 'WHEAT PRODUCTION', 'WHEAT YIELD', 'MAIZE AREA', 'MAIZE PRODUCTION', 'MAIZE YIELD', 'BARLEY AREA', 'BARLEY PRODUCTION', 'BARLEY YIELD', 'JOWAR AREA', 'JOWAR PRODUCTION', 'JOWAR YIELD', 'BAJRA AREA', 'BAJRA PRODUCTION', 'BAJRA YIELD', 'RAGI AREA', 'RAGI PRODUCTION', 'RAGI YIELD', 'SMALL MILLETS AREA', 'SMALL MILLETS PRODUCTION', 'SMALL MILLETS YIELD', 'SHREE ANNA /NUTRI CEREALS AREA', 'SHREE ANNA /NUTRI CEREALS PRODUCTION', 'SHREE ANNA /NUTRI CEREALS YIELD', 'NUTRI/COARSE CEREALS AREA', 'NUTRI/COARSE CEREALS PRODUCTION', 'NUTRI/COARSE CEREALS YIELD', 'CEREALS AREA', 'CEREALS PRODUCTION', 'CEREALS YIELD', 'TUR AREA', 'TUR PRODUCTION', 'TUR YIELD', 'GRAM AREA', 'GRAM PRODUCTION', 'GRAM YIELD', 'URAD AREA', 'URAD PRODUCTION', 'URAD YIELD', 'MOONG AREA', 'MOONG PRODUCTION', 'MOONG YIELD', 'LENTIL AREA', 'LENTIL PRODUCTION', 'LENTIL YIELD', 'OTHER PULSES AREA', 'OTHER PULSES PRODUCTION', 'OTHER PULSES YIELD', 'TOTAL PULSES AREA', 'TOTAL PULSES PRODUCTION', 'TOTAL PULSES YIELD', 'TOTAL FOOD GRAINS AREA', 'TOTAL FOOD GRAINS PRODUCTION', 'TOTAL FOOD GRAINS YIELD', 'GROUNDNUT AREA', 'GROUNDNUT PRODUCTION', 'GROUNDNUT YIELD', 'CASTORSEED AREA', 'CASTORSEED PRODUCTION', 'CASTORSEED YIELD', 'SESAMUM AREA', 'SESAMUM PRODUCTION', 'SESAMUM YIELD', 'NIGERSEED AREA', 'NIGERSEED PRODUCTION', 'NIGERSEED YIELD', 'SOYBEAN AREA', 'SOYBEAN PRODUCTION', 'SOYBEAN YIELD', 'SUNFLOWER AREA', 'SUNFLOWER PRODUCTION', 'SUNFLOWER YIELD', 'RAPESEED & MUSTARD AREA', 'RAPESEED & MUSTARD PRODUCTION', 'RAPESEED & MUSTARD YIELD', 'LINSEED AREA', 'LINSEED PRODUCTION', 'LINSEED YIELD', 'SAFFLOWER AREA', 'SAFFLOWER PRODUCTION', 'SAFFLOWER YIELD', 'TOTAL OIL SEEDS AREA', 'TOTAL OIL SEEDS PRODUCTION', 'TOTAL OIL SEEDS YIELD', 'SUGARCANE AREA', 'SUGARCANE PRODUCTION', 'SUGARCANE YIELD', 'COTTON AREA', 'COTTON PRODUCTION', 'COTTON YIELD', 'JUTE AREA', 'JUTE PRODUCTION', 'JUTE YIELD', 'MESTA AREA', 'MESTA PRODUCTION', 'MESTA YIELD', 'JUTE & MESTA AREA', 'JUTE & MESTA PRODUCTION', 'JUTE & MESTA YIELD', 'TOBACCO AREA', 'TOBACCO PRODUCTION', 'TOBACCO YIELD', 'SANNHEMP AREA', 'SANNHEMP PRODUCTION', 'SANNHEMP YIELD', 'GUARSEED AREA', 'GUARSEED PRODUCTION', 'GUARSEED YIELD']

In [11]:
df1 = df_Area.join(df_Production).join(df_Yield)
df1[l]

,RICE AREA,RICE PRODUCTION,RICE YIELD,WHEAT AREA,WHEAT PRODUCTION,WHEAT YIELD,MAIZE AREA,MAIZE PRODUCTION,MAIZE YIELD,BARLEY AREA,BARLEY PRODUCTION,BARLEY YIELD,JOWAR AREA,JOWAR PRODUCTION,JOWAR YIELD,BAJRA AREA,BAJRA PRODUCTION,BAJRA YIELD,RAGI AREA,RAGI PRODUCTION,RAGI YIELD,SMALL MILLETS AREA,SMALL MILLETS PRODUCTION,SMALL MILLETS YIELD,SHREE ANNA /NUTRI CEREALS AREA,...,TOTAL OIL SEEDS YIELD,SUGARCANE AREA,SUGARCANE PRODUCTION,SUGARCANE YIELD,COTTON AREA,COTTON PRODUCTION,COTTON YIELD,JUTE AREA,JUTE PRODUCTION,JUTE YIELD,MESTA AREA,MESTA PRODUCTION,MESTA YIELD,JUTE & MESTA AREA,JUTE & MESTA PRODUCTION,JUTE & MESTA YIELD,TOBACCO AREA,TOBACCO PRODUCTION,TOBACCO YIELD,SANNHEMP AREA,SANNHEMP PRODUCTION,SANNHEMP YIELD,GUARSEED AREA,GUARSEED PRODUCTION,GUARSEED YIELD
Year,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2020,457.69,1243.68,2717.0,311.25,1095.86,3521.0,98.92,316.47,3199.0,5.92,16.56,2796.0,43.78,48.12,1099.0,76.52,108.63,1420.0,11.59,19.98,1724.0,4.44,3.47,781.0,136.33,...,1247.0,48.51,4053.99,83566.0,132.86,352.48,451.0,6.22,89.53,2591.0,0.41,4.02,1782.0,6.62,93.54,2542.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021,462.79,1294.71,2798.0,304.59,1077.42,3537.0,99.58,337.30,3387.0,4.53,13.71,3025.0,38.01,41.51,1092.0,68.41,97.81,1430.0,12.18,17.01,1396.0,4.29,3.67,857.0,122.89,...,1312.0,51.75,4394.25,84906.0,123.72,311.18,428.0,6.29,97.62,2793.0,0.38,3.87,1831.0,6.67,101.49,2738.0,3.86,8.18,2118.0,0.13,0.51,722.0,26.30,11.83,450.0
2022,478.32,1357.55,2838.0,314.01,1105.54,3521.0,107.44,380.85,3545.0,6.28,19.13,3044.0,35.35,38.14,1079.0,75.72,114.31,1510.0,11.63,16.91,1454.0,4.28,3.84,898.0,126.98,...,1368.0,58.85,4905.33,83349.0,129.27,336.60,443.0,6.19,89.89,2614.0,0.39,4.03,1871.0,6.58,93.92,2570.0,3.79,7.70,2029.0,0.12,0.46,703.0,32.13,17.87,556.0
2023,478.28,1378.25,2882.0,318.33,1132.92,3559.0,112.41,376.65,3351.0,5.51,16.99,3082.0,40.76,47.37,1162.0,73.75,107.16,1453.0,12.15,16.70,1375.0,4.80,4.49,935.0,131.45,...,1314.0,57.40,4531.58,78953.0,126.88,325.22,436.0,5.98,92.52,2783.0,0.39,4.41,2033.0,6.37,96.92,2737.0,4.10,8.66,2109.0,0.09,0.40,801.0,30.89,16.65,539.0
2024,514.23,1490.74,2899.0,327.61,1175.07,3587.0,120.17,422.81,3518.0,6.05,18.44,3049.0,39.84,48.80,1225.0,72.10,108.63,1507.0,12.29,18.34,1492.0,4.42,4.38,992.0,128.64,...,1408.0,53.58,4501.16,84006.0,112.30,306.92,465.0,5.39,84.33,2814.0,0.31,3.15,1816.0,5.71,87.47,2759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df1.to_csv("All-India-20 to 24 Data.csv")